import pygame

image1 = pygame.image.load("pictures/e.png")
image1 = pygame.transform.scale(image1, (150, 150))
image2 = pygame.image.load("pictures/schwa.png")
image2 = pygame.transform.scale(image2, (150, 150))
image3 = pygame.image.load("pictures/ae.png")
image3 = pygame.transform.scale(image3, (150, 150))
image4 = pygame.image.load("pictures/dach.png")
image4 = pygame.transform.scale(image4, (150, 150))
image5 = pygame.image.load("pictures/hufeisen.png")
image5 = pygame.transform.scale(image5, (150, 150))
image6 = pygame.image.load("pictures/reversea.png")
image6 = pygame.transform.scale(image6, (150, 150))
image7 = pygame.image.load("pictures/dach_desc.png")
image7 = pygame.transform.scale(image7, (150, 150))
image8 = pygame.image.load("pictures/e_desc.png")
image8 = pygame.transform.scale(image8, (150, 150))
image_match = pygame.image.load("pictures/match_animation.png")
image_match2 = pygame.image.load("pictures/match_animation2.png")
image_lose1 = pygame.image.load("pictures/wrong_answer1.png")
cover_image = pygame.image.load("pictures/cover.png")
cover_image = pygame.transform.scale(cover_image, (150, 150))

animation = [image_match, image_match2]